#Config file with all parameters

url: 'http://vgibox.eu/repository/api.php'

# Parameters to have id list

parameters_id:
  action: 'query'
  format: 'json'
  list: 'categorymembers'
  #cmtitle: 'Category:VGI_Domain'
  cmtitle: 'Category:Publication'

# Paramaters to extract content of a page
parameters_extract_content:
  action: 'query'
  format: 'json'
  prop: 'revisions'
  rvprop: 'content'

output:
  file: 'abstracts'
  folder: 'Abstracts/'

options:
  multiple_file: false
  xml: true
