#Config ontologies file with all parameters

# ATTENTION: Variable path NEED ABSOLUTE PATH !
ontologies:
  path: '/home/damien/Workspace/master_project/data/ontologies'

abstract_folder: 'Results/Extracts/Multiple/'


# Decide if we want to write the file in rdf
rdf:
  write_rdf: true
  file_name: 'Results/Rdf/rdf_onto_extraction.rdf'
