#Config ontologies file with all parameters

# ATTENTION: Variable path NEED ABSOLUTE PATH !
ontologies:
  path: '/home/damien/Workspace/master_project/data/ontologies'

abstract_folder: 'Results/Extracts/Multiple/'
